### ISSUE TITLE
How do you set a timeout for a specific route?

### ISSUE THREAD

**Issue by nitrocode** [js-fullstack/koa-timeout-v2#2]
I'm using koa-router and I want to set different timeouts per route using your module. Is it possible?

**Comment by niftylettuce** [comment]
@nitrocode yes you could use this package or ours at <https://github.com/ladjs/koa-better-timeout>

basically ...

```js
const router = new Router();
router.get('/', theMiddlewareFunctionGoesHere, (ctx, next) => {
  // your middleware here
});
```

For this package you'd replace `theMiddlewareFunctionGoesHere` with `timeout()`.

For our package `koa-better-timeout`, you'd replace the `theMiddlewareFunctionGoesHere` with `new Timeout().middleware`.

Please close this issue, thanks!
